# Generated by Django 3.2.16 on 2023-02-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150, unique=True, verbose_name='')),
                ('dungeon_master', models.CharField(max_length=150, verbose_name='')),
                ('total_players', models.IntegerField()),
                ('discription', models.TextField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('Austria', (('Kasematten - Schlossbergbühne', 'Kasematten - Schlossbergbühne'), ('Bilderbox', 'Bilderbox'))), ('Germany', (('Le Royal - The Event hall', 'Le Royal - The Event hall'), ('Zapp Comics Games', 'Zapp Comics Games'), ('Comic Room', 'Comic Room'))), ('France', (('Len’s PC Gamer', 'Len’s PC Gamer'), ('G.E.E.K.S', 'G.E.E.K.S'), ('Librairie Comptoir de Reve', 'Librairie Comptoir de Reve'))), ('Italy', (('Star Comic Store Napoli', 'Star Comic Store Napoli'), ('Comix Green', 'Comix Green'), ('Infinity Comics', 'Infinity Comics'), ('Games & Geeks', 'Games & Geeks'))), ('Ireland', (('Tyrrelstown House', 'Tyrrelstown House'), ('Gloster House', 'Gloster House'), ('Reroll Games', 'Reroll Games'), ('The Gathering', 'The Gathering'))), ('Netherlands', (('Purple Dragon', 'Purple Dragon'), ('The Fantasy Realm', 'The Fantasy Realm'), ('Arnhem', 'Arnhem'), ('Warhammer', 'Warhammer'))), ('Spain', (('Gremio De Dragones', 'Gremio De Dragones'), ('Pulsar Store', 'Pulsar Store'), ('Dungeon Marvels', 'Dungeon Marvels'), ('Joc & Rol', 'Joc & Rol'))), ('United Kingtom (UK)', (('Geek Retreat Blackburn', 'Geek Retreat Blackburn'), ('4th Planet Games', '4th Planet Games'), ('Mutant Dice Games', 'Mutant Dice Games'), ('Lancaster Board and Sword', 'Lancaster Board and Sword')))], max_length=50)),
                ('booking_date', models.DateField()),
                ('booking_comments', models.TextField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
