# Generated by Django 3.2.16 on 2023-02-13 15:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('campaign_name', models.CharField(max_length=150, unique=True, verbose_name='')),
                ('dungeon_master', models.CharField(max_length=150, verbose_name='')),
                ('total_players', models.IntegerField()),
                ('discription', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_pics'),
        ),
        migrations.CreateModel(
            name='BookVenue',
            fields=[
                ('booking_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('venue', models.CharField(choices=[('Austria', (('1', 'Kasematten - Schlossbergbühne'), ('2', 'Bilderbox'))), ('Germany', (('1', 'Le Royal - The Event hall'), ('2', 'Zapp Comics Games'), ('3', 'Comic Room'))), ('France', (('1', 'Len’s PC Gamer'), ('2', 'G.E.E.K.S'), ('3', 'Librairie Comptoir de Reve'))), ('Italy', (('1', 'Star Comic Store Napoli'), ('2', 'Comix Green'), ('3', 'Infinity Comics'), ('4', 'Games & Geeks'))), ('Ireland', (('1', 'Tyrrelstown House'), ('2', 'Gloster House'), ('3', 'Reroll Games'), ('4', 'The Gathering'))), ('Netherlands', (('1', 'Purple Dragon'), ('2', 'The Fantasy Realm'), ('3', 'Arnhem'), ('4', 'Warhammer'))), ('Spain', (('1', 'Gremio De Dragones'), ('2', 'Pulsar Store'), ('3', 'Dungeon Marvels'), ('4', 'Joc & Rol'))), ('United Kingtom (UK)', (('1', 'Geek Retreat Blackburn'), ('2', '4th Planet Games'), ('3', 'Mutant Dice Games'), ('4', 'Lancaster Board and Sword')))], max_length=50)),
                ('booking_date', models.DateField()),
                ('booking_comments', models.TextField(blank=True, max_length=200)),
                ('total_players', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
