# Generated by Django 3.2.16 on 2023-05-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_alter_bookvenue_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvenue',
            name='campaigns',
            field=models.CharField(choices=[('OMW IT WORKS!', 'OMW IT WORKS!'), ('HPLEASE', 'HPLEASE'), ('IbegYou', 'IbegYou'), ('PLEEASSE', 'PLEEASSE'), ('KeepingItUp', 'KeepingItUp'), ('NowWe Hope', 'NowWe Hope'), ('HopefullyLastTest', 'HopefullyLastTest'), ('LizzysGang', 'LizzysGang'), ('QuackersSquad', 'QuackersSquad'), ('HopeLost', 'HopeLost'), ('The Dragons', 'The Dragons'), ('Dragon Masters', 'Dragon Masters'), ('HopeTrusters', 'HopeTrusters'), ('Johns', 'Johns'), ("Harry's Campaign", "Harry's Campaign"), ('Long nameda', 'Long nameda'), ('SecondCampaignName', 'SecondCampaignName')], max_length=150, unique=True),
        ),
    ]
