# Generated by Django 3.2.16 on 2023-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_auto_20230223_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvenue',
            name='campaigns',
            field=models.CharField(choices=[('Rout', 'Rout'), ('Long nameda', 'Long nameda'), ('SecondCampaignName', 'SecondCampaignName'), ('Longnameherew', 'Longnameherew')], default=None, max_length=150, unique=True),
        ),
    ]
