# Generated by Django 3.2.16 on 2023-02-26 17:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_alter_bookvenue_campaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='bookvenue',
            name='campaigns',
            field=models.CharField(choices=[('Johns', 'Johns'), ("Harry's Campaign", "Harry's Campaign"), ('Long nameda', 'Long nameda'), ('SecondCampaignName', 'SecondCampaignName'), ('Longnameherew', 'Longnameherew')], default=None, max_length=150, unique=True),
        ),
    ]
