# Generated by Django 3.2.16 on 2023-02-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_auto_20230226_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
