# Generated by Django 3.2.16 on 2023-02-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_auto_20230214_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookvenue',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookvenue',
            name='total_players',
        ),
        migrations.AlterField(
            model_name='bookvenue',
            name='booking_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
