# Generated by Django 3.2.16 on 2023-02-16 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booker', '0005_auto_20230216_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookvenue',
            name='booking_id',
        ),
        migrations.AlterField(
            model_name='bookvenue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
