# Generated by Django 3.2.16 on 2023-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0007_alter_bookvenue_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvenue',
            name='booking_date',
            field=models.DateField(unique=True),
        ),
    ]
